### ISSUE TITLE
皮皮虾解析的最近是不是更新策略了 之前的方法貌似不可以了

### ISSUE THREAD

**Issue by liuen12** [FioraLove/Net-Spider#33]

**Comment by FioraLove** [comment]
### As of 10/20/2020, 皮皮虾app更新了接口不再暴露无水印视频地址
奇怪点：

1. 任意分享的视频链接如下：
   - https://h5.pipix.com/s/3asShh（✅）
   - https://h5.pipix.com/s/JRjEVyT（✖）
   - https://h5.pipix.com/s/JAtW8Yg（✖）
   - https://h5.pipix.com/s/rR5Ppu（✅）
2. 发现有些视频链接，获取访问结果的json中的“comment”字段里居然藏有无水印的视频url
3. 有些分享链接的comment字段为空数组，有些又有值。想通过app分享链接百分百拿到无水印视频url感觉有点困难，除非知道内部视频数据api
