### ISSUE TITLE
来lssue一下

### ISSUE THREAD

**Issue by Ceekay992** [FioraLove/Net-Spider#47]
就算你注释了 我会用算我输.jpg

**Comment by Ceekay992** [comment]
对比了一下不会用的庫andc++ 我又会python了

**Comment by FioraLove** [comment]
> 就算你注释了 我会用算我输.jpg


哈哈，有什么地方不懂吗？遇到不懂的问题可以加我的QQ(*980710425*) 和另一个贡献者的QQ(*2876473037*)，都很乐意分享的O(∩_∩)O  O(∩_∩)O
