### ISSUE TITLE
快手解析异常

### ISSUE THREAD

**Issue by qinghuabumo** [FioraLove/Net-Spider#49]
快手解析异常 Need captcha  需要验证码~

**Comment by FioraLove** [comment]
> 快手解析异常 Need captcha 需要验证码~

hi~，我今天早上 **2021-03-12 09:38** 拿了[快手APP上的分享链接](https://v.kuaishou.com/cv2KST) 和 [快手Web端的视频链接](https://video.kuaishou.com/short-video/3x5j6vt2wkq4a2s?authorId=3xvuuywgds3338q&streamSource=find&area=homexxbrilliant) 都测试了，都是没有问题的，说明程序解析快手短视频的功能是没问题的。

- 出现滑块的原因：
   - 有可能是访问速度过快，触发了快手风控检测，建议解析每个url时程序休眠一段时间或使用代理IP，重现一下在什么情况下会出现反爬虫，然后对症下药
