### ISSUE TITLE
【小红书】无水印解析失效

### ISSUE THREAD

**Issue by FioraLove** [FioraLove/Net-Spider#57]

**Comment by ravizhan** [comment]
刚放学回家，抓包分析了一下小红书app，下面是一些结论

- URL `https://edith.xiaohongshu.com/api/sns/v3/note/videofeed?note_id=视频id`
> 视频id即
![image](https://user-images.githubusercontent.com/37010563/111867453-01f44580-89af-11eb-95e1-5c53af3d1c62.png)

- 请求参数 `xy-common-params`和`shield`
- `xy-common-params`
经过测试后，精简为`xy-common-params: sid=session.1616235340440156551519&build=6841002`
其中`sid`的前13位是登录时间的时间戳，精度为毫秒级，后面的九位不知道是啥，`build`是app的版本号
- `shield`
这个不知道是啥，实测每次重启app都会变，但是貌似不影响旧的(?)

![image](https://user-images.githubusercontent.com/37010563/111868223-a6788680-89b3-11eb-9927-c5d0c0b195a3.png)


- 请求成功后会返回json格式的字符串
![image](https://user-images.githubusercontent.com/37010563/111868168-57caec80-89b3-11eb-9565-290f5e5842e1.png)
其中`http://sns-video-hw.xhscdn.com/09da6e239abb0797a3181ea136d6e3adb8b63372_r`即为无水印地址

**Comment by FioraLove** [comment]
> 刚放学回家，抓包分析了一下小红书app，下面是一些结论
> 
> * URL `https://edith.xiaohongshu.com/api/sns/v3/note/videofeed?note_id=视频id`
> 
> > 视频id即
> > ![image](https://user-images.githubusercontent.com/37010563/111867453-01f44580-89af-11eb-95e1-5c53af3d1c62.png)
> 
> * 请求参数 `xy-common-params`和`shield`
> * `xy-common-params`
>   经过测试后，精简为`xy-common-params: sid=session.1616235340440156551519&build=6841002`
>   其中`sid`的前13位是登录时间的时间戳，精度为毫秒级，后面的九位不知道是啥，`build`是app的版本号
> * `shield`
>   这个不知道是啥，实测每次重启app都会变，但是貌似不影响旧的(?)
> 
> ![image](https://user-images.githubusercontent.com/37010563/111868223-a6788680-89b3-11eb-9927-c5d0c0b195a3.png)
> 
> * 请求成功后会返回json格式的字符串
>   ![image](https://user-images.githubusercontent.com/37010563/111868168-57caec80-89b3-11eb-9565-290f5e5842e1.png)
>   其中`http://sns-video-hw.xhscdn.com/09da6e239abb0797a3181ea136d6e3adb8b63372_r`即为无水印地址

哇！我这边更离谱！
我起先使用自己的手机IOS14+Fiddler Everywhere，发现居然有十几个参数，而且缺一不可。
然后我使用夜深模拟器+Xposed+JustTrustMe+Fiddler Everywhere，然后最离谱的就来了😂😂😂，我打开小红书APP，点击账号居然登录不了，无法输入任何字。退掉Xposed后，再次点击登录一直提示版本等级太低，我的APP是最新版本的。
你这边有空方便发一下的你的各种配置版本吗？

**Comment by EdisonCC** [comment]
> > 刚放学回家，抓包分析了一下小红书app，下面是一些结论
> > 
> > * URL `https://edith.xiaohongshu.com/api/sns/v3/note/videofeed?note_id=视频id`
> > 
> > > 视频id即
> > > ![image](https://user-images.githubusercontent.com/37010563/111867453-01f44580-89af-11eb-95e1-5c53af3d1c62.png)
> > 
> > 
> > 
> > * 请求参数 `xy-common-params`和`shield`
> > * `xy-common-params`
> >   经过测试后，精简为`xy-common-params: sid=session.1616235340440156551519&build=6841002`
> >   其中`sid`的前13位是登录时间的时间戳，精度为毫秒级，后面的九位不知道是啥，`build`是app的版本号
> > * `shield`
> >   这个不知道是啥，实测每次重启app都会变，但是貌似不影响旧的(?)
> > 
> > ![image](https://user-images.githubusercontent.com/37010563/111868223-a6788680-89b3-11eb-9927-c5d0c0b195a3.png)
> > 
> > * 请求成功后会返回json格式的字符串
> >   ![image](https://user-images.githubusercontent.com/37010563/111868168-57caec80-89b3-11eb-9565-290f5e5842e1.png)
> >   其中`http://sns-video-hw.xhscdn.com/09da6e239abb0797a3181ea136d6e3adb8b63372_r`即为无水印地址
> 
> 哇！我这边更离谱！
> 我起先使用自己的手机IOS14+Fiddler Everywhere，发现居然有十几个参数，而且缺一不可。
> 然后我使用夜深模拟器+Xposed+JustTrustMe+Fiddler Everywhere，然后最离谱的就来了😂😂😂，我打开小红书APP，点击账号居然登录不了，无法输入任何字。退掉Xposed后，再次点击登录一直提示版本等级太低，我的APP是最新版本的。
> 你这边有空方便发一下的你的各种配置版本吗？

用雷电可以登录小红书最新版， 
登录方法：模拟器先安装微博，登录微博，然后打开小红书用微博跳转登录

![image](https://user-images.githubusercontent.com/24759541/112743444-f06ff680-8fc9-11eb-8853-2891297108fb.png)

**Comment by EdisonCC** [comment]
大佬最近小红书有思绪吗

**Comment by EdisonCC** [comment]
小红书无水印图片下载
https://www.52pojie.cn/thread-1457463-1-1.html
(出处: 吾爱破解论坛)

**Comment by alienjun** [comment]
现在有方案了吗

**Comment by willwang-ai** [comment]
现在有解决方法了吗

**Comment by doufujushi** [comment]
现在有解决方法了吗

**Comment by ravizhan** [comment]
最近闲来无事又捣鼓了一下，偶然就发现了无水印的方法
例如 https://www.xiaohongshu.com/explore/6457b5be000000002702b029
打开响应可以看到如下内容
![image](https://github.com/FioraLove/Net-Spider/assets/37010563/8cfe5913-3c91-47b3-8ae6-12c9b834f19d)
将 `originVideoKey` 和前面的提到的 `http://sns-video-hw.xhscdn.com/` 拼接起来就是无水印地址
注意` \u002F` 需要转码为 `/`
例如 http://sns-video-hw.xhscdn.com/pre_post/1000g0cg2f5bv1fago0005oj2dklodepcik75800 (浏览器似乎不能正常播放，要下载再打开)
就。。。挺神奇的🤣🤣🤣
