### ISSUE TITLE
大佬有计划把解析接口 增加PHP版本吗

### ISSUE THREAD

**Issue by EdisonCC** [FioraLove/Net-Spider#58]
大佬有计划把解析接口 增加PHP版本吗？PHP版本放在服务器里比较方便，感谢！

**Comment by FioraLove** [comment]
> 大佬有计划把解析接口 增加PHP版本吗？PHP版本放在服务器里比较方便，感谢！

😂😂😂，不好意思呀，暂时还没有这方面的计划，后续会提供一个RESTful API（ 我的另一个项目 [NMSL](https://github.com/FioraLove/NMSL) 就是利用Django做后端，vue-cli作为前端，传入一个url，返回短视频无水印的json结果集）

说实话，我的php超烂的，连数组的基本函数都要查字典 (✿◕‿◕✿)  (✿◕‿◕✿)

**Comment by EdisonCC** [comment]
好的，感谢!
