### ISSUE TITLE
希望大佬能增加小红书、快手图集去水印下载功能，感谢！

### ISSUE THREAD

**Issue by EdisonCC** [FioraLove/Net-Spider#59]
希望大佬能增加小红书、快手图集去水印下载功能，感谢！

**Comment by FioraLove** [comment]
> 希望大佬能增加小红书、快手图集去水印下载功能，感谢！

您好
- 【快手图集】是一个单独的APP，还是快手APP中的某一项功能，方便发一个软件内容截图或分享一个你想要解析的视频url
-  【小红书】还在思考中，它的APP有点难，可能花费时间较久

**Comment by EdisonCC** [comment]
我找到一个小红书的 ，你参考一下，不知道还能不能用 https://github.com/Tammy-zting/python-xiaohongshu

快手图集不是单独的app，也是在快手里面的，不同的是一些人发的是视频，一些人发的是图片这样子，
这个是快手图集的链接 https://v.kuaishou.com/cYRkmv

**Comment by FioraLove** [comment]
> 我找到一个小红书的 ，你参考一下，不知道还能不能用 https://github.com/Tammy-zting/python-xiaohongshu
> 
> 快手图集不是单独的app，也是在快手里面的，不同的是一些人发的是视频，一些人发的是图片这样子，
> 这个是快手图集的链接 https://v.kuaishou.com/cYRkmv

ok，感谢，我抽时间看看快手图集。小红书的那个有点太老了，互联网的APP更新换代很快，所有我们一般都是看最近一个月更新的

**Comment by EdisonCC** [comment]
快手图集呢，他通过app保存就会有水印，所以只能通过解析，爬到他的地址出来进行下载

**Comment by FioraLove** [comment]
我刚刚已经在**develop**分支上提交了**快手图集**的解析，它的主要原理是：

 1.  通过APP里的分享获取视频url：https://v.kuaishou.com/cYRkmv
 2.  url会经过两次重定向，然后跳转到真实地址
 3.  图片就是在其网页元素img标签中，不是由异步请求获取的

希望你多分享几个小姐姐图集的url，我多测试测试😍😍😍。最好希望有PC端的链接，方便适配多端，我在电脑上没有找到

**Comment by EdisonCC** [comment]
PC端地址 ：https://live.kuaishou.com/u/RR1718190/3x4bduuh4uqrbxa?did=web_088cf239f6654844bce30eb5e3c3abca
https://live.kuaishou.com/u/mx278516/3xahgx5ya7u366a?did=web_088cf239f6654844bce30eb5e3c3abca
https://live.kuaishou.com/u/RR1718190/3xv86iwnyyquct4?did=web_088cf239f6654844bce30eb5e3c3abca

侧边里的相关推荐都是
![image](https://user-images.githubusercontent.com/24759541/112091245-f764c680-8bcf-11eb-913a-0a6c923a8205.png)

**Comment by FioraLove** [comment]
> PC端地址 ：https://live.kuaishou.com/u/RR1718190/3x4bduuh4uqrbxa?did=web_088cf239f6654844bce30eb5e3c3abca
> https://live.kuaishou.com/u/mx278516/3xahgx5ya7u366a?did=web_088cf239f6654844bce30eb5e3c3abca
> https://live.kuaishou.com/u/RR1718190/3xv86iwnyyquct4?did=web_088cf239f6654844bce30eb5e3c3abca
> 
> 侧边里的相关推荐都是
> ![image](https://user-images.githubusercontent.com/24759541/112091245-f764c680-8bcf-11eb-913a-0a6c923a8205.png)

少看点小姐姐呀，伤身子呀😣😣😣

**Comment by FioraLove** [comment]
@EdisonCC web端的快手图集经测试【**必须要登录**】才可以，若不登录的话，请求返回的结果是没有任何参考价值的，所以我推荐你使用APP中分享的图集链接来解析
我在【develop】分支上新提交了一版多端适配的。

**Comment by EdisonCC** [comment]
谢谢大佬

**Comment by 1893945** [comment]
版主，短视频无水印下载链接的获取办法是什么呀？
嗯，我的意思是怎么找到各个平台无水印视频的链接的
