### ISSUE TITLE
小红书解析 失效。下载的就是有水印的解析。

### ISSUE THREAD

**Issue by 9597865** [FioraLove/Net-Spider#60]
但，我看到 其他解析的站点。还是可以 做到去水印。不知道算法是什么？
http://xhslink.com/D28SGb

有水印
http://v.xiaohongshu.com/69cff08457e7f866d66fdf31410cb70396eec834_r_ln?sign=ffbd5ddbcaeb4d580e18e69bcc393de3&t=60576d80

无水印
http://sns-video-hw.xhscdn.com/526a436300c8dcb0df2072bad28d0bf9a843fa03_r_ln

**Comment by ravizhan** [comment]
目测是用的app的协议，这方面有待研究，具体见 https://github.com/FioraLove/Net-Spider/issues/57
