### ISSUE TITLE
关于 Python 依赖的版本问题

### ISSUE THREAD

**Issue by Kaiser925** [FioraLove/Net-Spider#63]
请问一下，当前所有的脚本的依赖包及其版本

**Comment by FioraLove** [comment]
您好，我使用的解释器及依赖包的版本为：

**python** ：3.7

依赖包主要用到如下几个

```
js2py==0.70
lxml==4.4.2
pyquery==1.4.0
pyexecjs==1.5.1
requests==2.22.0
```

如果仍有什么依赖问题，请告知😊

**Comment by FioraLove** [comment]
> 请问一下，当前所有的脚本的依赖包及其版本

您好，我使用的解释器及依赖包的版本为：

**python** ：3.7

依赖包主要用到如下几个

```
js2py==0.70
lxml==4.4.2
pyquery==1.4.0
pyexecjs==1.5.1
requests==2.22.0
```

如果仍有什么依赖问题，请告知😊

**Comment by Kaiser925** [comment]
@FioraLove 是否需要 Pipenv 对项目进行依赖管理

**Comment by FioraLove** [comment]
> @FioraLove 是否需要 Pipenv 对项目进行依赖管理

按标准流程是最好进行项目依赖管理，不过我们项目比较简单，依赖包也很简单，可以不用的。我觉得嗷，可以有，但没必要🤔

**Comment by Kaiser925** [comment]
好的，谢谢
