### ISSUE TITLE
ixigua 不能用

### ISSUE THREAD

**Issue by Kratos2** [FioraLove/Net-Spider#64]
看了大多数貌似都不能用啊   直接代码执行 是我执行的姿势不对么

**Comment by ravizhan** [comment]
确认是脚本失效了，预计下周修复

**Comment by FioraLove** [comment]
@Kratos2  西瓜🍉视频已修复了，若有什么问题请告知
@ravizhan 对项目的不离不弃，感激涕零，感恩戴德，感动天地(●'◡'●)
