### ISSUE TITLE
bilibili的视频下不了,,不知道是否跟地址有关

### ISSUE THREAD

**Issue by szy2k** [FioraLove/Net-Spider#65]
bilibili的视频下不了,,不知道是否跟地址有关,网页分享跟手机分享的地址是不一样的,,,但两个地址都是了一下都不可以

**Comment by FioraLove** [comment]
> bilibili的视频下不了,,不知道是否跟地址有关,网页分享跟手机分享的地址是不一样的,,,但两个地址都是了一下都不可以

感谢，哔哩哔哩视频下载已修复，手机APP上的分享地址，还要重定向一次后，才会变成BV号，新增了移动端的适配。
bilibili的视频格式是 **.m4s** 的，在浏览器上是无法打开的，而且还有必须携带一些浏览器指纹信息才能下载，你可以仔细看看我的**download函数**
